name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install mongosh CLI
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Wait for MongoDB to become healthy
        run: |
          for i in {1..30}; do
            mongosh --host mongo --username root --password example --authenticationDatabase admin --eval "db.adminCommand('ping')" && break
            echo "Waiting for MongoDB to be healthy..."
            sleep 5
          done

      - name: Run MongoDB connectivity test
        run: |
          mongosh --host mongo --username root --password example --authenticationDatabase admin --eval "db.stats()"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run SonarQube Analysis (Backend)
        uses: sonarsource/sonarqube-scan-action@v1.2
        with:
          projectBaseDir: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://127.0.0.1:9000

      - name: Run SonarQube Analysis (Frontend)
        uses: sonarsource/sonarqube-scan-action@v1.2
        with:
          projectBaseDir: ./frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://127.0.0.1:9000

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: nileshc8890/wanderlust-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: nileshc8890/wanderlust-frontend:latest

      - name: Trivy Scan - Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nileshc8890/wanderlust-backend:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Trivy Scan - Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nileshc8890/wanderlust-frontend:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: visiontech-aks
          resource-group: VisionTechRG1

      - name: Deploy to AKS
        run: |
          kubectl apply -f kubernetes/
